export const data = [
	{
		name: "myMovie React App",
		languages: "JavaScript, HTML, CSS",
		technologies: "React, Node, Express, Parcel, React Bootstrap",
		stack: "MERN",
		number: 1,
		website: "https://mymovieapp-brettranieri.netlify.app/",
		gitLink: "https://github.com/brett-ranieri/myMovie-client",
		description:
			"Fully responsive front end application built with React, React Bootstrap, and Parcel that allows users to interact with data stored in myMovie API. I also built the server side component on a MERN Stack. Users can sign up, save and update personal information, as well as create a list of their favorites movies.",
		shortDescription: "Front end React App that interacts with myMovie-database",
		type: "Bootcamp Project",
		images: [{ source: "./img/project/myMovie_1.png", alt: "screenshot of myMovie app" }],
	},
	{
		name: "myMovie-API",
		languages: "JavaScript",
		technologies: "MongoDB, Node.js, Express, Mongoose, MongoDB Atlas, Vercel, JSDoc",
		stack: "MERN",
		number: 2,
		website: "",
		gitLink: "https://github.com/brett-ranieri/movie-api",
		description:
			"Rest API made with MongoDB and hosted on Vercel. Allows users to store/update personal information (encrypts user passwords) and allows access to information about different movies, directors, and genres. CORS protected",
		shortDescription: "Rest API made with MongoDB that allows users to store and access data.",
		type: "Bootcamp Project",
		images: [{ source: "https://placehold.co/300x150", alt: "placeholder" }],
	},
	{
		name: "Pokedex",
		languages: "JavaScript, HTML, CSS",
		technologies: "Bootstrap",
		stack: "",
		number: 3,
		website: "https://brett-ranieri.github.io/first-js-app/",
		gitLink: "https://github.com/brett-ranieri/first-js-app",
		description:
			"This is my first application made with JavaScript. The goal was to use HTML, CSS and JS to create a web application that loads data from an external API and allow users to interact with the data points in detail. The Pokedex app communicates with the PokeAPI to load information on the first original 150 pokemon, allowing the user to browse this list and click for more details on any specific pokemon.",
		shortDescription:
			"First Javascript application ever made! Loads data from external API and allows user to interface.",
		type: "Bootcamp Project",
		images: [{ source: "./img/project/pokedex_1.png", alt: "screenshot of Pokedex" }],
	},
	{
		name: "Meet App",
		languages: "JavaScript",
		technologies: "React, Node, React Bootstrap, Recharts, SASS, Lighthouse",
		stack: "",
		number: 4,
		website: "https://brett-ranieri.github.io/meet/",
		gitLink: "https://github.com/brett-ranieri/meet",
		description:
			"Serverless, progressive web application built with React. After logging in with Gmail users can use the app to retrieve data from a google calendar via Google API. Information is then displayed in multiple ways, including responsive charts from Recharts. This project also showcases TDD and incorporates Object Oriented Programming.",
		shortDescription:
			"Serverless, progressive web application built with React. Allows authenticated users to browse/filter events provided from Google Calendar API.",
		type: "Bootcamp Project",
		images: [
			{ source: "./img/project/meet_1.png", alt: "screenshot of meet app" },
			{ source: "./img/project/meet_2.png", alt: "screenshot of meet app" },
		],
	},
	{
		name: "Hello World",
		languages: "JavaScript, HTML, CSS",
		technologies: "React, React Native, Expo, Firebase",
		stack: "",
		number: 5,
		website: "",
		gitLink: "https://github.com/brett-ranieri/hello-world",
		description:
			"Chat App made with React Native. Allows users to log in and join a chat room where they can send text messages, pictures (taken with camera or shared from photos), and share their devices location. All data stored in a Firebase database. ",
		shortDescription: "React Native chat app that uses Firebase database.",
		type: "Bootcamp Project",
		images: [
			{ source: "./img/project/hello_1.png", alt: "screenshot of hello world app" },
			{ source: "./img/project/hello_2.png", alt: "screenshot of hello world app" },
		],
	},
	{
		name: "MyMovie Angular Frontend",
		languages: "TypeScript, HTML, CSS",
		technologies: "Angular, Angular Material, JSDoc",
		stack: "",
		number: 6,
		website: "https://brett-ranieri.github.io/myMovie-Angular-client/",
		gitLink: "https://github.com/brett-ranieri/myMovie-Angular-client",
		description:
			"Frontend UI for the myMovie-API that is made with Angular. Same functioninality as that of React Frontend but this project allowed me to get a better understanding of TypeScript and Two-way data binding.",
		shortDescription: "Angular Front end application for myMovie-API",
		type: "Bootcamp Project",
		images: [{ source: "https://placehold.co/300x150", alt: "placeholder" }],
	},
	{
		name: "Seventh Project",
		languages: "Lots",
		technologies: "None",
		stack: "",
		number: 7,
		website: "https://brett-ranieri.github.io/myMovie-Angular-client/",
		gitLink: "https://github.com/brett-ranieri/myMovie-Angular-client",
		description: "I'm a long descriptiong, look at how long I am.",
		shortDescription: "I'm short",
		type: "Bootcamp Project",
		images: [{ source: "https://placehold.co/300x150", alt: "placeholder" }],
	},
];
