export const data = [
	{
		name: "myMovie React App",
		languages: "JavaScript, HTML, CSS",
		technologies: "React, Node, Express, Parcel, React Bootstrap",
		stack: "MERN",
		number: 1,
		website: "https://mymovieapp-brettranieri.netlify.app/",
		gitLink: "https://github.com/brett-ranieri/myMovie-client",
		description:
			"Fully responsive front end application built with React, React Bootstrap, and Parcel that allows users to interact with data stored in myMovie API. I also built the server side component on a MERN Stack. Users can sign up, save and update personal information, as well as create a list of their favorites movies.",
		shortDescription: "Front end React App that interacts with myMovie-database",
		type: "Bootcamp Project",
		images: [
			{ source: "./img/project/myMovie_1.png", alt: "screenshot of myMovie app" },
			{ source: "./img/project/myMovie_2.png", alt: "screenshot of profile page" },
			{ source: "./img/project/myMovie_3.png", alt: "screenshot of movie details" },
			{ source: "./img/project/myMovie_4.png", alt: "screenshot of movie details further down" },
			{ source: "./img/project/myMovie_5.png", alt: "screenshot of sign up form" },
		],
	},
	{
		name: "myMovie-API",
		languages: "JavaScript",
		technologies: "MongoDB, Node.js, Express, Mongoose, MongoDB Atlas, Vercel, JSDoc",
		stack: "MERN",
		number: 2,
		website: "",
		gitLink: "https://github.com/brett-ranieri/movie-api",
		description:
			"Rest API made with MongoDB and hosted on Vercel. Allows users to store/update personal information (encrypts user passwords) and allows access to information about different movies, directors, and genres. CORS protected",
		shortDescription: "Rest API made with MongoDB that allows users to store and access data.",
		type: "Bootcamp Project",
		images: [
			{ source: "./img/project/api_1.png", alt: "screenshot of MongoDB Atlas collection" },
			{ source: "./img/project/api_2.png", alt: "screenshot of Postman endpoint testing" },
			// { source: "https://placehold.co/300x150", alt: "placeholder5" },
		],
	},
	{
		name: "THIS Portfolio Website",
		languages: "JavaScript, HTML, CSS",
		technologies: "React, Material Tailwind, HOSTING SITE",
		stack: "",
		number: 7,
		website: "",
		gitLink: "https://github.com/brett-ranieri/web-port-react",
		description:
			"As it's my first FULLY personal project, I needed to feature this website here. Aside from all of the standard navigational areas to explore I have tried to build in some easter eggs. The screenshots highlight the areas you should hunt in, but that's all I'm gonna say about that...up to you to do the rest!",
		shortDescription:
			"Look, it's the website you're on right...click for more info on some built in Easter Eggs!",
		type: "Personal Project",
		images: [
			{ source: "./img/project/port_1.png", alt: "screenshot of first easter egg" },
			{ source: "./img/project/port_2.png", alt: "screenshot of second easter egg" },
			{ source: "https://placehold.co/300x150", alt: "placeholder15" },
		],
	},
	{
		name: "Meet App",
		languages: "JavaScript",
		technologies: "React, Node, React Bootstrap, Recharts, SASS, Lighthouse",
		stack: "",
		number: 4,
		website: "https://brett-ranieri.github.io/meet/",
		gitLink: "https://github.com/brett-ranieri/meet",
		description:
			"Serverless, progressive web application built with React. After logging in with Gmail users can use the app to retrieve data from a google calendar via Google API. Information is then displayed in multiple ways, including responsive charts from Recharts. This project also showcases TDD and incorporates Object Oriented Programming.",
		shortDescription:
			"Serverless, progressive web application built with React. Allows authenticated users to browse/filter events provided from Google Calendar API.",
		type: "Bootcamp Project",
		images: [
			{ source: "./img/project/meet_1.png", alt: "screenshot of meet app" },
			{ source: "./img/project/meet_2.png", alt: "another screenshot of meet app" },
			{ source: "./img/project/meet_3.png", alt: "screenshot of google login" },
			{ source: "./img/project/meet_4.png", alt: "screenshot of offline search" },
			{ source: "./img/project/meet_5.png", alt: "close up of offline search" },
		],
	},
	{
		name: "Hello World",
		languages: "JavaScript, HTML, CSS",
		technologies: "React, React Native, Expo, Firebase",
		stack: "",
		number: 5,
		website: "",
		gitLink: "https://github.com/brett-ranieri/hello-world",
		description:
			"Chat App made with React Native. Allows users to log in and join a chat room where they can send text messages, pictures (taken with camera or shared from photos), and share their devices location. All data stored in a Firebase database. ",
		shortDescription: "React Native chat app that uses Firebase database.",
		type: "Bootcamp Project",
		images: [
			{ source: "./img/project/hello_1.png", alt: "screenshot of hello world app" },
			{ source: "./img/project/hello_2.png", alt: "another screenshot of hello world app" },
			{ source: "https://placehold.co/300x150", alt: "placeholder9" },
		],
	},
	{
		name: "MyMovie Angular Frontend",
		languages: "TypeScript, HTML, CSS",
		technologies: "Angular, Angular Material, TypeDoc",
		stack: "",
		number: 6,
		website: "https://brett-ranieri.github.io/myMovie-Angular-client/",
		gitLink: "https://github.com/brett-ranieri/myMovie-Angular-client",
		description:
			"Frontend UI for the myMovie-API that is made with Angular. Same functioninality as that of React Frontend but this project allowed me to get a better understanding of TypeScript and Two-way data binding.",
		shortDescription: "Angular Front end application for myMovie-API",
		type: "Bootcamp Project",
		images: [
			{ source: "./img/project/angular_1.png", alt: "screenshot of angular movies" },
			{ source: "./img/project/angular_2.png", alt: "screenshot of angular summary modal" },
			{ source: "./img/project/angular_3.png", alt: "screenshot of angular update info form" },
		],
	},
	{
		name: "Pokedex",
		languages: "JavaScript, HTML, CSS",
		technologies: "Bootstrap",
		stack: "",
		number: 3,
		website: "https://brett-ranieri.github.io/first-js-app/",
		gitLink: "https://github.com/brett-ranieri/first-js-app",
		description:
			"This is my first application made with JavaScript. The goal was to use HTML, CSS and JS to create a web application that loads data from an external API and allow users to interact with the data points in detail. The Pokedex app communicates with the PokeAPI to load information on the first original 150 pokemon, allowing the user to browse this list and click for more details on any specific pokemon.",
		shortDescription:
			"First Javascript application ever made! Loads data from external API and allows user to interface.",
		type: "Bootcamp Project",
		images: [
			{ source: "./img/project/pokedex_1.png", alt: "screenshot of Pokedex" },
			{ source: "./img/project/pokedex_2.png", alt: "screenshot of search" },
			{ source: "./img/project/pokedex_3.png", alt: "screenshot of pikachu modal" },
		],
	},
];
